### ISSUE TITLE
[Medium] Number of cycles parameter does not work

### ISSUE THREAD

**Issue by jsimonclark** [BattMoTeam/BattMo-gui#29]
Changing the number of cycles parameter in the protocol menu does not give the correct behaviour. It looks like the time domain is updated (i.e. the simulation duration is longer) but it just discharges once and then stays there.

**Comment by LorenaH84** [comment]
Yeah good point. The 'number_of_cycles' parameter is not passed on to BattMo.jl, but it is used to calculate the total simulation time and number of time steps... 

@xavierr is it possible to pass the number of cycles to battmo.jl and simulate multiple cycles?
