### ISSUE TITLE
Change the results plotting package

### ISSUE THREAD

**Issue by jsimonclark** [BattMoTeam/BattMo-gui#32]
The plots from packages like plotly (or similar) look much nicer in streamlit than matplotlib. Let's update that on the Results page.

**Comment by LorenaH84** [comment]
Done! You can check the changes in the dev branch. Any more suggestions to the results page?

**Comment by jsimonclark** [comment]
Nice! Did you know that GitHub has a feature where you can use your commit message to link to specific issues? For example, if your commit message is something like:

- changed plotting package to plotly, resolves #32

Here are some more recommendations for writing good commit messages: https://medium.com/@saeid/10-essential-practices-for-better-git-commits-and-why-they-matter-3cfc420bf53e
